# Generated by Django 5.2.7 on 2026-02-25 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.TextField(help_text='Path to the stored image file')),
                ('embedding_vector', models.JSONField(default=list, help_text='Float array of the CNN embedding vector')),
                ('file_hash', models.CharField(help_text='SHA-256 hash of the file for deduplication', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_image_path', models.TextField(help_text='Path to the uploaded query image')),
                ('query_hash', models.CharField(help_text='SHA-256 hash of the query image', max_length=128)),
                ('search_source', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('both', 'Both')], default='local', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_type', models.CharField(help_text='Type: object, text, logo, etc.', max_length=50)),
                ('label_value', models.CharField(help_text='Detected label value', max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.originaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_detected', models.BooleanField(default=False)),
                ('name_detected', models.BooleanField(default=False)),
                ('age_detected', models.BooleanField(default=False)),
                ('address_detected', models.BooleanField(default=False)),
                ('phone_detected', models.BooleanField(default=False)),
                ('total_flags', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_analysis', to='api.searchquery')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('local', 'Local'), ('google', 'Google')], max_length=10)),
                ('external_url', models.TextField(blank=True, help_text='URL for Google web matches', null=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_results', to='api.originaldocument')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.searchquery')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
    ]
