# Generated by Django 5.2.7 on 2026-05-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='matched_image_path',
            field=models.TextField(blank=True, help_text='Path to a locally-stored candidate image (for web search results)', null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('bing', 'Bing')], max_length=10),
        ),
    ]
