# Generated by Django 5.2.7 on 2026-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchresult_matched_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='search_source',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('bing', 'Bing'), ('both', 'Both')], default='local', max_length=10),
        ),
    ]
